name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: symfony
          MYSQL_USER: symfony
          MYSQL_PASSWORD: symfony
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql, zip, gd
        coverage: none

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env', '.env');"

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest --no-interaction

    - name: Create database
      run: php bin/console doctrine:database:create --if-not-exists --no-interaction

    - name: Run tests
      run: php bin/console cache:clear --env=test

  docker:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build -t symfony-app .

    - name: Test Docker image
      run: |
        docker run -d -p 8000:80 --name symfony-test symfony-app
        sleep 10
        curl -f http://localhost:8000 || exit 1
        docker stop symfony-test
        docker rm symfony-test
